# @package _global_

# to execute this experiment run:
# python -m iid.material_diffusion

defaults:
  - /logger: wandb
  - /model: material
  - /environment@_here_: default

# ======================== DATAMODULE ============================

data:
  input_path: data/InteriorVerse/2025/osu_office/20250314_am_sunny/0220_im.exr
  gt_path: data/InteriorVerse/2025/osu_office/20250314_am_sunny/0220_albedo.exr
  include_metadata: True

output:
  folder: output
  as_dataset: False

# ======================== ENVIRONMENT ============================

task_name: material_diffusion

seed: 0

device: auto

